CREATE TABLE `jobportal`.`appointment` (`name` TEXT NOT NULL , `email` TEXT NOT NULL , `package` TEXT NOT NULL , `date` DATE NULL , `id` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS diagnostic_packages (
	id INT NOT NULL,
	name VARCHAR(180) NOT NULL,
	description TEXT NOT NULL,
	pricing INT NOT NULL,
	category VARCHAR(100) NOT NULL,
	tags JSON NOT NULL,
	related_packages JSON NOT NULL,
	popularity TINYINT UNSIGNED NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY uq_diagnostic_packages_name (name),
	KEY idx_diagnostic_packages_category (category),
	KEY idx_diagnostic_packages_pricing (pricing),
	KEY idx_diagnostic_packages_popularity (popularity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO diagnostic_packages (id, name, description, pricing, category, tags, related_packages, popularity) VALUES
	(2, 'Fasting Blood Sugar', 'Measures blood glucose levels after fasting for 8-10 hours. Helps in early detection of diabetes and monitoring long-term sugar control.', 200, 'Diabetes', '["sugar", "diabetes"]', '[3]', 85),
	(3, 'Postprandial Blood Sugar', 'Checks blood sugar levels after meals. Useful for understanding how the body processes glucose and managing diabetes effectively.', 250, 'Diabetes', '["sugar"]', '[2]', 75),
	(4, 'Random Blood Sugar', 'Measures blood sugar at any time of the day. Helps in quick screening and identifying abnormal glucose levels.', 150, 'Diabetes', '["sugar"]', '[2, 3]', 70),
	(5, 'HbA1C Test', 'Shows average blood sugar levels over the past 2-3 months. Helps in diagnosing and monitoring diabetes control.', 1200, 'Diabetes', '["diabetes"]', '[2, 3]', 90),
	(6, 'Insulin Test', 'Measures insulin hormone levels in blood. Helps detect insulin resistance and diabetes risk.', 2000, 'Diabetes', '["insulin"]', '[5]', 80),
	(7, 'Thyroid Profile', 'Includes T3, T4, and TSH tests to evaluate thyroid function. Helps detect hormonal imbalance and metabolism issues.', 1500, 'Thyroid', '["thyroid"]', '[8, 9]', 90),
	(8, 'TSH Test', 'Measures thyroid stimulating hormone. Helps diagnose thyroid disorders and monitor treatment.', 500, 'Thyroid', '["thyroid"]', '[7]', 80),
	(9, 'Free T3 Test', 'Measures active thyroid hormone T3. Helps assess metabolism and thyroid health.', 600, 'Thyroid', '["thyroid"]', '[7]', 70),
	(10, 'Free T4 Test', 'Measures thyroxine hormone. Helps detect thyroid imbalance and metabolic conditions.', 600, 'Thyroid', '["thyroid"]', '[7]', 70),
	(11, 'Complete Blood Count', 'Analyzes blood components like RBC, WBC, and platelets. Helps detect infections, anemia, and overall health condition.', 500, 'General', '["blood"]', '[12]', 95),
	(12, 'ESR Test', 'Measures inflammation in the body. Helps detect infections and chronic diseases.', 200, 'General', '["inflammation"]', '[11]', 70),
	(13, 'CRP Test', 'Detects inflammation and infection levels. Helps monitor immune response and disease activity.', 600, 'General', '["inflammation"]', '[12]', 80),
	(14, 'Liver Function Test', 'Evaluates liver enzymes and proteins. Helps detect liver diseases and monitor liver health.', 1800, 'Liver', '["liver"]', '[15]', 85),
	(15, 'SGPT (ALT)', 'Measures liver enzyme ALT. Helps detect liver damage and monitor liver conditions.', 400, 'Liver', '["liver"]', '[14]', 70),
	(16, 'Kidney Function Test', 'Evaluates kidney health using creatinine and urea levels. Helps detect kidney disease early.', 1500, 'Kidney', '["kidney"]', '[17]', 85),
	(17, 'Creatinine Test', 'Measures kidney filtration efficiency. Helps monitor kidney function.', 400, 'Kidney', '["kidney"]', '[16]', 75),
	(18, 'Urea Test', 'Measures waste products in blood. Helps assess kidney function and hydration status.', 350, 'Kidney', '["kidney"]', '[16]', 70),
	(19, 'Vitamin D Test', 'Measures vitamin D levels. Helps improve bone strength and immunity.', 2500, 'Vitamin', '["vitamin"]', '[20]', 85),
	(20, 'Vitamin B12 Test', 'Measures vitamin B12 levels. Helps prevent anemia and nerve damage.', 1800, 'Vitamin', '["vitamin"]', '[19]', 80),
	(21, 'Iron Test', 'Measures iron levels in blood. Helps diagnose anemia and fatigue causes.', 700, 'Iron', '["iron"]', '[22]', 75),
	(22, 'Ferritin Test', 'Measures stored iron in body. Helps detect iron deficiency or overload.', 1200, 'Iron', '["iron"]', '[21]', 78),
	(23, 'TIBC Test', 'Measures iron binding capacity. Helps evaluate iron metabolism.', 900, 'Iron', '["iron"]', '[21]', 70),
	(24, 'Calcium Test', 'Measures calcium levels. Important for bone health and muscle function.', 500, 'General', '["calcium"]', '[]', 70),
	(25, 'Magnesium Test', 'Measures magnesium levels. Helps maintain nerve and muscle health.', 900, 'General', '["mineral"]', '[]', 65),
	(26, 'Phosphorus Test', 'Measures phosphorus levels. Supports bone and kidney health.', 500, 'General', '["mineral"]', '[]', 60),
	(27, 'Electrolyte Panel', 'Measures sodium, potassium, chloride levels. Helps maintain fluid balance and nerve function.', 800, 'General', '["electrolyte"]', '[]', 80),
	(28, 'Urine Routine Test', 'Analyzes urine composition. Helps detect infections and kidney disorders.', 300, 'General', '["urine"]', '[]', 90),
	(29, 'Amylase Test', 'Measures pancreatic enzyme. Helps detect pancreatic disorders.', 800, 'Pancreas', '["pancreas"]', '[30]', 65),
	(30, 'Lipase Test', 'Measures lipase enzyme. Helps diagnose pancreatitis.', 1200, 'Pancreas', '["pancreas"]', '[29]', 65),
	(31, 'Dengue NS1 Antigen Test', 'Detects dengue virus in early stage. Helps in quick diagnosis and timely treatment during dengue outbreaks.', 1500, 'Infection', '["dengue"]', '[32]', 85),
	(32, 'Dengue IgG/IgM Test', 'Detects dengue antibodies. Useful for confirming dengue infection and monitoring recovery stage.', 1800, 'Infection', '["dengue"]', '[31]', 80),
	(33, 'Malaria Test', 'Detects malaria parasites in blood. Helps in early diagnosis and prevents complications from infection.', 900, 'Infection', '["malaria"]', '[]', 70),
	(34, 'Typhoid Test (Widal)', 'Detects typhoid infection. Helps diagnose fever causes and start proper treatment early.', 800, 'Infection', '["typhoid"]', '[]', 75),
	(35, 'Hepatitis B Surface Antigen', 'Detects Hepatitis B infection. Helps in early diagnosis and prevention of liver complications.', 600, 'Infection', '["hepatitis"]', '[36]', 85),
	(36, 'Hepatitis C Antibody', 'Detects Hepatitis C infection. Helps in early treatment and liver disease prevention.', 1200, 'Infection', '["hepatitis"]', '[35]', 75),
	(37, 'HIV 1 & 2 Test', 'Screens for HIV infection. Early detection helps in better management and prevention.', 1000, 'Infection', '["hiv"]', '[]', 85),
	(38, 'VDRL Test', 'Screens for syphilis infection. Helps in early detection and treatment of sexually transmitted infections.', 500, 'Infection', '["std"]', '[]', 70),
	(39, 'Prolactin Test', 'Measures prolactin hormone levels. Helps diagnose hormonal imbalance and fertility issues.', 1500, 'Hormone', '["hormone"]', '[40]', 70),
	(40, 'Testosterone Test', 'Measures testosterone levels. Helps assess male health, fertility, and hormonal balance.', 2200, 'Hormone', '["hormone"]', '[39]', 75),
	(41, 'Estrogen Test', 'Measures estrogen hormone. Helps evaluate reproductive health and hormonal balance in females.', 2000, 'Hormone', '["hormone"]', '[]', 70),
	(42, 'Cortisol Test', 'Measures stress hormone cortisol. Helps diagnose stress disorders and adrenal gland issues.', 1800, 'Hormone', '["cortisol"]', '[]', 75),
	(43, 'Progesterone Test', 'Measures progesterone hormone. Important for pregnancy monitoring and reproductive health.', 2000, 'Hormone', '["hormone"]', '[]', 70),
	(44, 'FSH Test', 'Measures follicle-stimulating hormone. Helps assess fertility and reproductive system health.', 1800, 'Hormone', '["fertility"]', '[45]', 70),
	(45, 'LH Test', 'Measures luteinizing hormone. Helps diagnose ovulation and fertility issues.', 1800, 'Hormone', '["fertility"]', '[44]', 70),
	(46, 'Uric Acid Test', 'Measures uric acid levels. Helps diagnose gout and joint-related issues.', 400, 'General', '["uric"]', '[]', 80),
	(47, 'Rheumatoid Factor Test', 'Detects rheumatoid arthritis. Helps diagnose joint inflammation and autoimmune disorders.', 800, 'General', '["arthritis"]', '[]', 75),
	(48, 'Anti-CCP Test', 'Confirms rheumatoid arthritis. Helps in early diagnosis and treatment planning.', 2500, 'General', '["arthritis"]', '[47]', 70),
	(49, 'D-Dimer Test', 'Measures clot formation. Helps detect blood clot disorders and deep vein thrombosis.', 2500, 'Cardio', '["clot"]', '[]', 75),
	(50, 'Troponin I Test', 'Detects heart muscle damage. Helps diagnose heart attack quickly.', 2000, 'Cardio', '["heart"]', '[49]', 85),
	(51, 'CPK-MB Test', 'Measures cardiac enzyme. Helps assess heart muscle injury.', 1800, 'Cardio', '["heart"]', '[50]', 75),
	(52, 'Blood Group Test', 'Determines blood type. Important for transfusions and medical emergencies.', 300, 'General', '["blood"]', '[]', 90),
	(53, 'Coagulation Profile', 'Measures blood clotting ability. Helps detect bleeding disorders and monitor therapy.', 2000, 'General', '["clot"]', '[]', 75),
	(54, 'Prothrombin Time (PT)', 'Measures blood clotting time. Helps assess bleeding risk and liver function.', 700, 'General', '["clot"]', '[53]', 70),
	(55, 'INR Test', 'Standardized clotting test. Helps monitor blood thinning medications.', 700, 'General', '["clot"]', '[54]', 75),
	(56, 'Stool Routine Test', 'Analyzes stool sample. Helps detect digestive issues, infections, and parasites.', 300, 'General', '["stool"]', '[]', 80),
	(57, 'Occult Blood Test', 'Detects hidden blood in stool. Helps screen for gastrointestinal bleeding.', 500, 'General', '["stool"]', '[56]', 70),
	(58, 'PSA Test', 'Measures prostate-specific antigen. Helps detect prostate issues in men.', 1500, 'Cancer', '["prostate"]', '[]', 75),
	(59, 'CA-125 Test', 'Measures tumor marker CA-125. Helps detect ovarian cancer risk.', 2500, 'Cancer', '["cancer"]', '[]', 70),
	(60, 'CEA Test', 'Measures carcinoembryonic antigen. Helps monitor certain cancers and treatment progress.', 2200, 'Cancer', '["cancer"]', '[]', 70);

